### PR TITLE
 Added date created field in projects table

### PR DESCRIPTION
**Pull request by adii21-Ux**

### CODE REVIEW

**Comment by tdruez** [comment]
@adii21-Ux you are displaying the model `created_date` while labelling it "Date Completed" in the UI.
Those are not the same thing.

**Comment by adii21-Ux** [comment]
Oh ok will fix it

**Comment by adii21-Ux** [comment]
@tdruez do you know any way I can get date completed of project because theres no field regarding that

**Comment by tdruez** [comment]
@adii21-Ux there's no concept of completion date at the project level.

**Pull request closed without merging**
