### PR TITLE
Upgraded to Django 4 and other related modules also

### LINKED ISSUE #384: Upgrade to Django 4.x

### PR DESCRIPTION
**Pull request by Pratyush1606**
Upgraded to Django 4.0.3 and other modules to the latest version.

Changes in Django 4.0 releases:
* Python compatibility
  Django 4.0 supports Python 3.8, 3.9, and 3.10. I have removed Python 3.6 and Python 3.7 from `setup.cfg` and updated CI

* zoneinfo default timezone implementation
  The Python standard library’s [zoneinfo](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo) is now the default timezone implementation in Django. I have removed `pytz` from the requirements. [zoneinfo](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo) is part of the Python standard library from Python 3.9. The backports.zoneinfo package is automatically installed alongside Django if you are using Python 3.8.
The present version of the codebase is using the `timezone` imported from `django.utils` for getting the present time using `timezone.now()` which works fine as previous in this newer version. [Reference](https://docs.djangoproject.com/en/4.0/topics/i18n/timezones/#time-zones)

* Minor Features
  1. [https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf](https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf)
    The changes mentioned in this feature are related to [CSRF_TRUSTED_ORIGINS](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CSRF_TRUSTED_ORIGINS) settings which our codebase is not concerned with. 

  2. [https://docs.djangoproject.com/en/4.0/releases/4.0/#requests-and-responses](https://docs.djangoproject.com/en/4.0/releases/4.0/#requests-and-responses)
    The changes mentioned in this feature are related to [SECURE_CROSS_ORIGIN_OPENER_POLICY](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_CROSS_ORIGIN_OPENER_POLICY) settings which also doesn't affect any change in our dependencies.

  3. [https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf-trusted-origins-changes](https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf-trusted-origins-changes) and [https://docs.djangoproject.com/en/4.0/releases/4.0/#configuring-it-may-now-be-required](https://docs.djangoproject.com/en/4.0/releases/4.0/#configuring-it-may-now-be-required) 
    For the changes in [CSRF_TRUSTED_ORIGINS](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CSRF_TRUSTED_ORIGINS) settings, no changes are we are including `csrf_token` in every form requests like of POST methods. 

  4. [https://docs.djangoproject.com/en/4.0/releases/4.0/#securitymiddleware-no-longer-sets-the-x-xss-protection-header](https://docs.djangoproject.com/en/4.0/releases/4.0/#securitymiddleware-no-longer-sets-the-x-xss-protection-header)
    No changes are required. 

Resolves #384 

Signed-off-by: Pratyush1606 <jaiswalpratyush2015@gmail.com>

### CODE REVIEW

**Comment by Pratyush1606** [comment]
@pombredanne Can you please review this pr?

**Review by pombredanne — COMMENTED** [review]
Thank you!
We need to run all the tests too.... Did you check they were passing?

**Comment by Pratyush1606** [comment]
@pombredanne I have merged it. Can you please approve running workflows?

**Comment by Pratyush1606** [comment]
@pombredanne  @tdruez Some tests are failing because Django 4.0+ requires Python 3.8+ and those tests are having Python versions below that. Can you tell me how to proceed further?

**Comment by Pratyush1606** [comment]
@tdruez So should I start working on reviewing those security details or move to other issues for right now?

**Comment by tdruez** [comment]
@Pratyush1606 I would not consider the upgrade complete without addressing those points.

**Comment by Pratyush1606** [comment]
@tdruez I will look into those points and will make changes.

**Comment by Pratyush1606** [comment]
> Upgraded to Django 4.0.3 and other modules to the latest version.
> 
> Changes in Django 4.0 releases:
> 
> * Python compatibility
>   Django 4.0 supports Python 3.8, 3.9, and 3.10. I have removed Python 3.6 and Python 3.7 from `setup.cfg` and updated CI
> * zoneinfo default timezone implementation
>   The Python standard library’s [zoneinfo](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo) is now the default timezone implementation in Django. I have removed `pytz` from the requirements. [zoneinfo](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo) is part of the Python standard library from Python 3.9. The backports.zoneinfo package is automatically installed alongside Django if you are using Python 3.8.
>   The present version of the codebase is using the `timezone` imported from `django.utils` for getting the present time using `timezone.now()` which works fine as previous in this newer version. [Reference](https://docs.djangoproject.com/en/4.0/topics/i18n/timezones/#time-zones)
> * Minor Features
>   
>   1. https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf
>      The changes mentioned in this feature are related to [CSRF_TRUSTED_ORIGINS](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CSRF_TRUSTED_ORIGINS) settings which our codebase is not concerned with.
>   2. https://docs.djangoproject.com/en/4.0/releases/4.0/#requests-and-responses
>      The changes mentioned in this feature are related to [SECURE_CROSS_ORIGIN_OPENER_POLICY](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_CROSS_ORIGIN_OPENER_POLICY) settings which also doesn't affect any change in our dependencies.
>   3. https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf-trusted-origins-changes and https://docs.djangoproject.com/en/4.0/releases/4.0/#configuring-it-may-now-be-required
>      For the changes in [CSRF_TRUSTED_ORIGINS](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CSRF_TRUSTED_ORIGINS) settings, no changes are we are including `csrf_token` in every form requests like of POST methods.
>   4. https://docs.djangoproject.com/en/4.0/releases/4.0/#securitymiddleware-no-longer-sets-the-x-xss-protection-header
>      No changes are required.
> 
> Resolves #384
> 
> Signed-off-by: Pratyush1606 [jaiswalpratyush2015@gmail.com](mailto:jaiswalpratyush2015@gmail.com)

**Comment by Pratyush1606** [comment]
@tdruez I went through the release of Django 4.0 and compared and analysed the changes. I have made the changes. I have also updated the PR description according to that only. Can you please have a look?

**Comment by tdruez** [comment]
@Pratyush1606 thanks for your contribution. See https://github.com/nexB/scancode.io/pull/418 for some extra changes and the merge into main branch.
Cheers 👍

**Pull request closed without merging**
