### PR TITLE
1287 purldb scan worker update

### PR DESCRIPTION
**Pull request by JonoYang**
This PR updates the `purldb-scan-worker` management command to send project results back using a new addon pipeline, `send_project_results`. This pipeline is appended to the list of pipelines to be run on a package, allowing the worker that handles the project execution to send back the data when all of the pipelines have been run. This allows us to not have the main task loop to monitor a single project run for completion in order to return data, and allows us to request multiple scan projects and work on them simultaneously. A new option, `--max-concurrent-projects`, has been added to set the number of purldb packages that can be requested and processed at once.

### CODE REVIEW

**Comment by tdruez** [comment]
@JonoYang The code looks fine but I don't feel great about adding a specialized pipeline only useful in the context of the PurlDB worker.

Couldn't we use the existing Webhook system for this instead?

**Comment by JonoYang** [comment]
@tomd I forgot about the webhook functions on the Project model. I will revise my code to use that instead.

**Comment by JonoYang** [comment]
@tomd I am looking at the webhook code and its relation to Projects and Runs. I see that in https://github.com/nexB/scancode.io/blob/main/scanpipe/tasks.py#L72 that we send back the project results after every Run on a Project. I would like to send back the results after all of the requested pipelines are run, as is the behavior of my code that adds the `send_project_results` pipeline. I have the idea to add a flag or some other attribute on Project to tell scancode.io when to process webhooks. I would like your opinion on the best way of triggering a webhook reply once all Project Runs are completed.

**Comment by tdruez** [comment]
>  I see that in https://github.com/nexB/scancode.io/blob/main/scanpipe/tasks.py#L72 that we send back the project results after every Run on a Project. I would like to send back the results after all of the requested pipelines are run,

Yes, I think that's a good opportunity to improve the Webhook system.
We could add a flag as you suggested to control if the webhook should be sent after each pipeline completion, or only at the end. 
We need to take into account that a pipeline (last or not) may fail and we need to decide what should happen to the Wehbook in that case.
Also, we need to define the default behavior. Posting only when all pipelines have been completed as default probably makes the most sense. With maybe a `send_on_failure` flag enabled by default.

**Comment by tdruez** [comment]
@JonoYang Added ``results_url`` and ``summary_url`` in the Webhook payload in https://github.com/nexB/scancode.io/pull/1326/files 

> We could add a flag as you suggested to control if the webhook should be sent after each pipeline completion, or only at the end.

Actually in the short term, since the `next_run` value is available in the payload, could your receiving view check if all the runs have completed to trigger the import process?

**Comment by JonoYang** [comment]
> We need to take into account that a pipeline (last or not) may fail and we need to decide what should happen to the Wehbook in that case. Also, we need to define the default behavior. Posting only when all pipelines have been completed as default probably makes the most sense. With maybe a `send_on_failure` flag enabled by default.

For what it's worth, in the context of the `purldb-scan-worker` command, if any of the requested pipelines failed, then we consider the entire Project to have failed and then send back a response to the purldb with that status.

> Actually in the short term, since the next_run value is available in the payload, could your receiving view check if all the runs have completed to trigger the import process?

Do you mean having the receiver (purldb) poll to see if the project is done? The endpoint that issues and handles the package scan requests on purldb currently does not poll outstanding package scan requests, but just waits for updates from the worker.

**Comment by tdruez** [comment]
@JonoYang The code looks good! Is this ready for merge or do you plan to add more?

**Comment by JonoYang** [comment]
I have nothing else to add. This is good to go for me

**Comment by tdruez** [comment]
Meged! @JonoYang feel free to close https://github.com/nexB/scancode.io/issues/1287 if completed 🚀

**Pull request merged**
