### PR TITLE
Add CTRL+k, GH to go back & search in Codebase Resource Details

### PR DESCRIPTION
**Pull request by swastkk**
Closes https://github.com/nexB/scancode.io/issues/870
**Tasks**

- [x] Add CTRL+k & GH to go back in Codebase Resources.
- [ ] Add Search bar just like Codebase Resource List page.

Screenshots Attached

Screenshot from 2024-03-12 21-09-32

Signed-off-by- swastkk <swastkk@gmail.com>

### CODE REVIEW

**Comment by tdruez** [comment]
@swastkk The idea of #870 is to open an advanced search bar when using the CTRL+k shortcut, not to emulate a "go back".

**Comment by swastkk** [comment]
Yes, i got the idea, inside the Codebase Resource details, there would be an addition of Search Bar just like in the Resource list with a shortcut of CTRL+K
And the GH to go back in the Resource List.
Right?

**Comment by tdruez** [comment]
> And the GH to go back in the Resource List.
> Right?

There is no need to duplicate the browser "go back" feature. The "GH" reference in the initial issue stands for GitHub. I'm not sure what you mean by "the GH to go back".

The purpose of this task is to implement a new contextual search box. As an example, use <Ctrl + K> on GitHub.

**Comment by swastkk** [comment]
> > And the GH to go back in the Resource List.
> > Right?
> 
> There is no need to duplicate the browser "go back" feature. The "GH" reference in the initial issue stands for GitHub. I'm not sure what you mean by "the GH to go back".
> 
> The purpose of this task is to implement a new contextual search box. As an example, use <Ctrl + K> on GitHub.

Yes, i got the idea i have made an search box just like the github will push in a while,

**Pull request closed without merging**
