### PR TITLE
Display summary data

### PR DESCRIPTION
**Pull request by JonoYang**
This PR modifies the project detail view to the information from the updated summary plugin for projects that run the `scan_package` pipeline. This is still a rough work in progress.
image

### CODE REVIEW

**Comment by JonoYang** [comment]
> @JonoYang could you rebase this one on the latest main? Also, fontawesome is already available in the statics as js lib https://github.com/nexB/scancode.io/blob/main/scancodeio/static/fontawesome-5.15.1.all.min.js Why adding the css version?

I'm not to familiar with front-end development on Django and ended up cargo culting code.

**Comment by tdruez** [comment]
> I'm not familiar with front-end development on Django and ended up cargo culting code.

No worries, let's simply remove the additional fontawesome library files.

**Comment by JonoYang** [comment]
@tdruez That would be most optimal to get this feature out quickly, though I would also be interested to learn more about how to make congruent UI elements that fit the style of existing elements.

**Comment by tdruez** [comment]
> @JonoYang I would also be interested to learn more about how to make congruent UI elements that fit the style of existing elements.

Check the 2 latest commit to get an idea on how I would refine the templates.
Currently (still room for improvements):
Screenshot 2022-07-14 at 22 46 41

**Pull request merged**
