### PR TITLE
Docs update for collation error in make postgresdb

### PR DESCRIPTION
**Pull request by swastkk**
Documents the https://github.com/nexB/scancode.io/issues/604
Screenshot- 
Screenshot_2023-02-18_06-43-27

Signed-off-by- swastik <swastkk@gmail.com>

### CODE REVIEW

**Comment by tdruez** [comment]
@swastkk thanks for your input, but this content is a bit to specific to your setup for the main documentation. 
We need to refine into something more generic about the potential conflicts between local db templates and scancodeio requirements.

**Comment by swastkk** [comment]
> @swastkk thanks for your input, but this content is a bit to specific to your setup for the main documentation. We need to refine into something more generic about the potential conflicts between local db templates and scancodeio requirements.

Yes, I was also thinking the same, so will update the PR accordingly.

**Comment by swastkk** [comment]
> @swastkk thanks for your input, but this content is a bit too specific to your setup for the main documentation. We need to refine into something more generic about the potential conflicts between local db templates and scancodeio requirements.

Yes, I have made the generalised changes in https://github.com/nexB/scancode.io/pull/615/commits/c87631ded94a0e7699d5c86d8c5bc6365c967238 have a look at 
Screenshot_2023-02-25_07-50-18

**Comment by tdruez** [comment]
@swastkk thanks for your input, I've made some edits and committed as https://github.com/nexB/scancode.io/commit/c2d8f0d6bd3504cdecfd79748a6192389bf06c1b

**Pull request closed without merging**
