### PR TITLE
Add instructions for vulnerablecode integration

### PR DESCRIPTION
**Pull request by TG1999**

### CODE REVIEW

**Comment by tdruez** [comment]
@TG1999 Could you add an introduction paragraph about the context of this integration.
You added the "how" but we also need the "why".

Also, a section about the usage of the `find_vulnerabilities` pipeline would be useful, following the configuration parts.

**Comment by TG1999** [comment]
@tdruez done!

**Comment by tdruez** [comment]
It would be more interesting to display screenshots about the actual vulnerability results of running the pipeline instead of showing how to add and run a pipeline, which is already cover in other tutorial.

**Comment by TG1999** [comment]
@tdruez done!

**Pull request merged**
