### PR TITLE
Add document section on Pipeline Packaging

### PR DESCRIPTION
**Pull request by AvishrantsSh**
- Adds a new document section describing pipeline registration
- Adds an example of pipeline packaging using the Custom Pipeline example.

Signed-off-by: Avishrant Sharma <avishrants@gmail.com>

PR for #267

### CODE REVIEW

**Comment by pombredanne** [comment]
@AvishrantsSh Thanks! is there more to it coming up?

**Comment by AvishrantsSh** [comment]
> @AvishrantsSh Thanks! is there more to it coming up?

Yes! That was just an initial draft of documentation. I'll be updating it shortly. 

Do you have any suggestions regarding this part of the documentation?

**Comment by pombredanne** [comment]
> Do you have any suggestions regarding this part of the documentation?

I would like to have an end-to-end single way documented. Ideally this could even include a cookiecutter or a dedicated skeleton that would take all the guesswork out of the equation. A mere link to https://packaging.python.org/tutorials/packaging-projects/ does not seem enough for the packaging part.

**Comment by tdruez** [comment]
Hi @hyounes4560 could you have a look at the new content and refine as needed? Thanks :)

**Review by hyounes4560 — APPROVED** [review]

**Comment by hyounes4560** [comment]
Hey @AvishrantsSh, great work; I added minor improvements. I'm not sure what "Adds a new document section describing pipeline registration" means? The registration section was already there. FYI @tdruez

**Pull request merged**
