### PR TITLE
Docker: run as non-root user, use venv

### LINKED ISSUE #260: Use virtualenv in Docker container
Using a virtualenv ensures that we know the exact packages of python versions made available to us. This is helps avoid surprise-ful behaviors.

This also needs to be done in scancodeIO

### LINKED ISSUE #399: run scancodeio as non-root user in docker

### PR DESCRIPTION
**Pull request by aalexanderr**
1. Run as non-elevated user by default
2. Install scancodeio in venv
3. Make it possible to set up UNAME/UID/GID on buildtime
4. Move scancodeio from /app to /opt to be more in-line with:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html
5. Set cache to /tmp as it is disposable after build
6. Upgrade pip to have less red in build log

Resolves #260
Resolves #399

Signed-off-by: Alexander Mazuruk <a.mazuruk@samsung.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks!

**Comment by tdruez** [comment]
Hi @aalexanderr this looks great. I see it's still labeled as WIP, anything else you planned to add?

**Comment by pombredanne** [comment]
gentle ping

**Comment by aalexanderr** [comment]
sorry for late come-back. added home dir (scancode-toolkit cache defaults to this dir), set group id for opt, should be ready to merge

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/821 using some of the ideas form this PR.
Thanks @aalexanderr !

**Pull request closed without merging**
