### PR TITLE
Add the license policies tutorial

### LINKED ISSUE #337: Add license policies tutorial in documentation
A suggested by @Atharex in https://github.com/nexB/scancode.io/issues/335#issuecomment-933457620, that feature is not well presented and hidden deep in the settings.

Paragraphs ideas for the tutorial:

1. General explanation about license policies and compliance alert
2. How to create a policies file, details about the format
3. Define the location of the policies file in the settings
4. How the compliance alert ok/warning/error/missing works
 ```
ok = self.Compliance.OK
error = self.Compliance.ERROR
warning = self.Compliance.WARNING
missing = self.Compliance.MISSING

  if error in alerts:
      return error
  elif warning in alerts:
      return warning
  elif missing in alerts:
      return missing
  return ok
```
5. Run a pipeline and look at the policies results

### PR DESCRIPTION
**Pull request by hyounes4560**
• Update the index file
Signed-off-by: Hanan Younes hyounes4560@conestogac.on.ca

Closes #337

### CODE REVIEW

**Comment by hyounes4560** [comment]
@tdruez FYI; not very sure about the example though!

**Comment by tdruez** [comment]
@hyounes4560 I've made some refinements and additions to the new tutorial.
Could you have a last look at it before the merge?

**Comment by hyounes4560** [comment]
@tdruez looks good to me

**Comment by tdruez** [comment]
@hyounes4560 thanks for your input ⭐

**Pull request merged**
