### PR TITLE
Add django-probes for wait_for_database

### PR DESCRIPTION
**Pull request by aalexanderr**
This feature is nice-to-have for Kubernetes/OpenShift deployments making
start up of app more streamlined by giving ability for K8s/OS to hold off running
 app until database is up.

As per it's docs it supports all db engines that Django supports:
https://pypi.org/project/django-probes/
License: BSD-3-Clause

Related: #335

### CODE REVIEW

**Comment by pombredanne** [comment]
This is sleek. Thanks!

**Comment by pombredanne** [comment]
This is sleek. Thanks!

**Comment by pombredanne** [comment]
I guess there is no easy way to have a test for this, right?

**Comment by pombredanne** [comment]
@cco3 would this be something that could make sense for you too?
@Atharex ping too, you were on some issues related to this

**Comment by cco3** [comment]
I'm not sure what our use for it would be.  We have our instance set up with a remote DB.

**Comment by aalexanderr** [comment]
OK so when deploying the app, the DB initialization is done via Django, yet it doesn't provide us with a nice interface for checking if DB is actually up. 
It allows to use the same container with same settings as for runtime to wait with initialization before the database is ready for it.
Another nice-to-have thing would be to do the same for Redis before workers are spawned.
I'll check in a bit how docker-compose up brings everything up but it might be worth making use of there too in this PR.

**Pull request merged**
