### PR TITLE
Implement a ScanForVirus Pipeline #1182

### PR DESCRIPTION
**Pull request by tdruez**

### CODE REVIEW

**Review by pombredanne — APPROVED** [review]
This looks decent... what's the hold to merge?

**Comment by tdruez** [comment]
> what's the hold to merge?

The structure is there, we now have to handle the output from ClamAV and store that data in the db.

**Comment by pombredanne** [comment]
> The structure is there, we now have to handle the output from ClamAV and store that data in the db.

@tdruez I would store this in extra_data at first.

**Comment by pombredanne** [comment]
... And/or report an error message if there is a virus detected?

**Review by pombredanne — APPROVED** [review]
Looking great! Thanks.

**Pull request merged**
