### PR TITLE
Add ref to make archiving easier to understand

### PR DESCRIPTION
**Pull request by silverhook**
+ minor typo fix

### CODE REVIEW

**Comment by tdruez** [comment]
@silverhook Thanks for your contribution but your are missing the Signoff in your commit message. Please check https://scancodeio.readthedocs.io/en/latest/contributing.html#code-contributions in order to fix this so we can merge your PR ;)

**Comment by silverhook** [comment]
@pombredanne said I could simply use the web ui for it.

If it’s possible to add DCO through the web ui, happy to do that. If I need to re-create the PR locally and push again, happy to do that too. Please advise :)

**Comment by pombredanne** [comment]
@silverhook you can do it either locally and force push, or you can add your signoff in a comment here and we can handle it from there.

**Comment by tdruez** [comment]
Included in https://github.com/nexB/scancode.io/commit/1ba99cb625364e695393023e17cc563d392f629a

**Pull request closed without merging**
