### PR TITLE
Add a scancodeio_version field to the Run model

### PR DESCRIPTION
**Pull request by tdruez**
Also add errors, resources, and packages count in the Project details API view

### CODE REVIEW

**Comment by tdruez** [comment]
@JonoYang this PR should address your suggestions in https://github.com/nexB/scancode.io/issues/288
Please have a look and let me know ;)

**Review by aalexanderr — CHANGES_REQUESTED** [review]
I think this line should be removed in this PR: 
https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/output.py#L158
as version will get serialized with each Run

**Comment by tdruez** [comment]
@aalexanderr we still want to keep track of the version that was used to generate the output though.

**Comment by aalexanderr** [comment]
@tdruez makes sense, thanks for the reply! I'm unsure how to dismiss my review?

**Review by aalexanderr — APPROVED** [review]

**Comment by JonoYang** [comment]
@tdruez This is perfect. Thanks!

**Review by JonoYang — APPROVED** [review]

**Pull request merged**
